#!/bin/bash

# Test New Registration Features
# This script helps you test the new profile fields

echo "=========================================="
echo "Testing New Registration Features"
echo "=========================================="
echo ""

echo "The server is running correctly!"
echo "Service name: AttendanceService"
echo "RMI port: 1100"
echo ""

echo "To test the NEW registration features:"
echo ""
echo "1. Start the client:"
echo "   ./run.sh client"
echo ""
echo "2. Click 'Register' button"
echo ""
echo "3. Test STUDENT registration:"
echo "   - First Name: Test"
echo "   - Last Name: Student"
echo "   - Username: teststudent"
echo "   - Email: test@student.com"
echo "   - Phone Number: 1234567890 (NEW - optional)"
echo "   - Gender: Male (NEW)"
echo "   - Account Type: STUDENT"
echo "   - Class Section: A"
echo "   - Profile Photo: (NEW - optional, click Choose Photo)"
echo "   - Password: Test@123"
echo "   - Confirm Password: Test@123"
echo ""
echo "4. Test TEACHER registration:"
echo "   - First Name: Test"
echo "   - Last Name: Teacher"
echo "   - Username: testteacher"
echo "   - Email: test@teacher.com"
echo "   - Phone Number: 9876543210 (NEW - optional)"
echo "   - Gender: Female (NEW)"
echo "   - Account Type: TEACHER"
echo "   - Department: Computer Science (NEW - REQUIRED!)"
echo "   - Profile Photo: (NEW - optional)"
echo "   - Password: Test@123"
echo "   - Confirm Password: Test@123"
echo ""
echo "=========================================="
echo "NEW FIELDS TO TEST:"
echo "=========================================="
echo "✓ Phone Number field (optional)"
echo "✓ Gender dropdown (Male/Female/Other)"
echo "✓ Department field (teachers only, required)"
echo "✓ Profile Photo upload (optional, max 5MB)"
echo ""
echo "=========================================="
echo "EXISTING USERS (for login testing):"
echo "=========================================="
echo ""

# Check if database is accessible
if command -v mysql &> /dev/null; then
    echo "Checking existing users in database..."
    mysql -u root -p -e "USE Wolde; SELECT username, email, role FROM USERS LIMIT 10;" 2>/dev/null
    if [ $? -ne 0 ]; then
        echo "Could not access database. Default users:"
        echo ""
        echo "Admin:"
        echo "  Username: admin"
        echo "  Email: admin@attendance.system"
        echo "  Password: Admin@123"
        echo ""
        echo "Teacher:"
        echo "  Username: teacher1"
        echo "  Email: teacher1@attendance.system"
        echo "  Password: Teacher@123"
        echo ""
        echo "Student:"
        echo "  Username: student1"
        echo "  Email: student1@attendance.system"
        echo "  Password: Student@123"
    fi
else
    echo "Default users:"
    echo ""
    echo "Admin:"
    echo "  Username: admin"
    echo "  Email: admin@attendance.system"
    echo "  Password: Admin@123"
    echo ""
    echo "Teacher:"
    echo "  Username: teacher1"
    echo "  Email: teacher1@attendance.system"
    echo "  Password: Teacher@123"
    echo ""
    echo "Student:"
    echo "  Username: student1"
    echo "  Email: student1@attendance.system"
    echo "  Password: Student@123"
fi

echo ""
echo "=========================================="
echo "TROUBLESHOOTING:"
echo "=========================================="
echo ""
echo "If login fails with 'Invalid username or password':"
echo "1. Make sure you're using the correct email/username"
echo "2. Make sure you're using the correct password"
echo "3. Try registering a new account with the NEW fields"
echo ""
echo "If 'wolde@gmail.com' doesn't exist:"
echo "1. Register a new account with that email"
echo "2. Or use one of the default accounts above"
echo ""
echo "=========================================="
echo "DOCUMENTATION:"
echo "=========================================="
echo "- QUICK_START_NEW_FEATURES.md - Quick guide"
echo "- REGISTRATION_FORM_VISUAL_GUIDE.md - Visual guide"
echo "- IMPLEMENTATION_COMPLETE.md - Complete summary"
echo ""
